// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMYIUD3vMTyuBhgIzwh-CQGh0Bi8jy_ug',
    appId: '1:62972437754:web:3ee50a514d05c385bf5543',
    messagingSenderId: '62972437754',
    projectId: 'kotton-kandy',
    authDomain: 'kotton-kandy.firebaseapp.com',
    storageBucket: 'kotton-kandy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVY612KiORqjetK3JV6P-s3HuhcC3ArJI',
    appId: '1:62972437754:android:d54272021c49b850bf5543',
    messagingSenderId: '62972437754',
    projectId: 'kotton-kandy',
    storageBucket: 'kotton-kandy.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-dg1BqpTUcQ5heBEfulqCbm79FsoXT5Y',
    appId: '1:62972437754:ios:059fdb979122bdeabf5543',
    messagingSenderId: '62972437754',
    projectId: 'kotton-kandy',
    storageBucket: 'kotton-kandy.firebasestorage.app',
    iosBundleId: 'com.example.kottonkandy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-dg1BqpTUcQ5heBEfulqCbm79FsoXT5Y',
    appId: '1:62972437754:ios:059fdb979122bdeabf5543',
    messagingSenderId: '62972437754',
    projectId: 'kotton-kandy',
    storageBucket: 'kotton-kandy.firebasestorage.app',
    iosBundleId: 'com.example.kottonkandy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMYIUD3vMTyuBhgIzwh-CQGh0Bi8jy_ug',
    appId: '1:62972437754:web:25af28d42c4ae4bbbf5543',
    messagingSenderId: '62972437754',
    projectId: 'kotton-kandy',
    authDomain: 'kotton-kandy.firebaseapp.com',
    storageBucket: 'kotton-kandy.firebasestorage.app',
  );
}
