// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6-JxVBuoEQME1j2NS8Aa4wTl-5DZG8yI',
    appId: '1:423357722783:web:4b882a0b5b923a06d632aa',
    messagingSenderId: '423357722783',
    projectId: 'kotton-kandy-beauty-bar',
    authDomain: 'kotton-kandy-beauty-bar.firebaseapp.com',
    storageBucket: 'kotton-kandy-beauty-bar.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChmwoi-7ZdMTIWuig7bh-JyWj2qu9R6k4',
    appId: '1:423357722783:android:d8f1c5715b484fbbd632aa',
    messagingSenderId: '423357722783',
    projectId: 'kotton-kandy-beauty-bar',
    storageBucket: 'kotton-kandy-beauty-bar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb8qg1tj4NFDwAvgb57ZUWJYaql5oiHa4',
    appId: '1:423357722783:ios:38026b14c43588c9d632aa',
    messagingSenderId: '423357722783',
    projectId: 'kotton-kandy-beauty-bar',
    storageBucket: 'kotton-kandy-beauty-bar.firebasestorage.app',
    iosBundleId: 'com.example.kottonkandy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb8qg1tj4NFDwAvgb57ZUWJYaql5oiHa4',
    appId: '1:423357722783:ios:38026b14c43588c9d632aa',
    messagingSenderId: '423357722783',
    projectId: 'kotton-kandy-beauty-bar',
    storageBucket: 'kotton-kandy-beauty-bar.firebasestorage.app',
    iosBundleId: 'com.example.kottonkandy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6-JxVBuoEQME1j2NS8Aa4wTl-5DZG8yI',
    appId: '1:423357722783:web:8f8254ce15e743d2d632aa',
    messagingSenderId: '423357722783',
    projectId: 'kotton-kandy-beauty-bar',
    authDomain: 'kotton-kandy-beauty-bar.firebaseapp.com',
    storageBucket: 'kotton-kandy-beauty-bar.firebasestorage.app',
  );
}
